# Generated by Django 4.0.1 on 2022-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_fb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url_insta',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url_linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url_twitter',
            field=models.URLField(null=True),
        ),
    ]
