# Generated by Django 4.0.1 on 2022-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_url_fb_user_url_insta_user_url_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_git',
            field=models.URLField(null=True, verbose_name='Url-GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_fb',
            field=models.URLField(null=True, verbose_name='Url-Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_insta',
            field=models.URLField(null=True, verbose_name='Url-Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_linkedin',
            field=models.URLField(null=True, verbose_name='Url-Linkedin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_twitter',
            field=models.URLField(null=True, verbose_name='Url-Twitter'),
        ),
    ]
