# Generated by Django 4.0.1 on 2022-01-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_url_git_alter_user_url_fb_alter_user_url_insta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url_twitter',
        ),
    ]
