# Generated by Django 4.0.1 on 2022-01-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_url_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_fb',
            field=models.URLField(blank=True, null=True, verbose_name='Url-Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_git',
            field=models.URLField(blank=True, null=True, verbose_name='Url-GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_insta',
            field=models.URLField(blank=True, null=True, verbose_name='Url-Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Url-Linkedin'),
        ),
    ]
