# Generated by Django 4.0.1 on 2022-01-30 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_room_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
